### ISSUE TITLE
About the java gui forms with events 

### ISSUE THREAD

**Issue by neymarsabin** [aruna02/javalearning#3]
Please add the gui form that you developed in the java class today.

**Comment by aruna02** [comment]
I have added it

**Comment by cdrrazan** [comment]
oh i think it wil be also useful for me. :+1: :package:

**Comment by cdrrazan** [comment]
@neymarsabin how about implementing in #jruby?

**Comment by neymarsabin** [comment]
Yupp implementing that in jruby would be awesome thing to do...
